title: Ritvik Gupta
description: Data Scientist /Analyst with over two years of experience extracting insights from complex data sets having python and machine learning tool expertise. Translated technical findings into business solutions that can be implemented for delivery. Eager to contribute expertise to data-driven transformational initiatives with a Go Get It Attitude.

show_downloads: false
theme: jekyll-theme-cayman
 	plugins:
 	- jekyll-seo-tag
 	author: Barud
