title: Ritvik Gupta
description: "Data Scientist/Analyst | Python & Machine Learning Expert | Transforming Data into Actionable Insights"

# Show site elements
show_downloads: false
show_related: true

# Theme Configuration
remote_theme: pages-themes/minimal@v0.2.0
# Add a theme-specific setting for navigation
minima:
  skin: dark # Choose between 'dark' or 'light' based on preference

# Social Media Links - Update with your actual usernames
social_links:
  linkedin: https://www.linkedin.com/in/ritvik-gupta-81852618b/
  email: gritvik8@gmail.com

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# SEO Tag plugin for better SEO
seo:
  type: Person
  name: Ritvik Gupta
  role: Data Scientist/Analyst
  social:
    - linkedin: https://www.linkedin.com/in/ritvik-gupta-81852618b/


# Enable Disqus comments on posts (optional) - Replace with your Disqus shortname
disqus:
  shortname: Ritvik
