title: Ritvik Gupta
description: "Data Scientist/Analyst | Python & Machine Learning Expert | Transforming Data into Actionable Insights"

# Show downloads button (true to show, false to hide)
show_downloads: false

# Theme Configuration
remote_theme: pages-themes/minimal@v0.2.0

# Social Media Links
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# SEO settings
seo:
  type: Person
  name: Ritvik Gupta
  role: Data Scientist/Analyst
  links:
    - url: https://www.linkedin.com/in/ritvik-gupta-81852618b/
      name: LinkedIn
    - url: https://github.com/01ritvik
      name: GitHub


disqus:
  shortname: yourshortname

# Navigation Bar (Add or remove items as needed)
navigation:
  - title: Publications
    url: https://www.ijser.in/archives/v10i12/SE221206135738.pdf
    url: https://www.ijser.in/archives/v11i8/SE23822002659.pdf

